import proImage from '@/assets/propertyImage.png';

export const propertiesData = [
  {
    id: 1,
    title: 'Palm Harbor',
    price: 2095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 56,
    yearBuilt: 2019,
    tenants: 8,
    request: 12,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Palm Harbor neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 2,
    title: 'Beverly Springfield',
    price: 2795,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 46,
    yearBuilt: 1999,
    tenants: 12,
    request: 12,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 3,
    title: 'Faulkner Ave',
    price: 4095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 23,
    yearBuilt: 2023,
    tenants: 12,
    request: 12,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 4,
    title: 'St. Crystal',
    price: 1095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 21,
    yearBuilt: 2020,
    tenants: 12,
    request: 19,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 5,
    title: 'Cove Red',
    price: 3095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Archive',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 16,
    yearBuilt: 2012,
    tenants: 10,
    request: 11,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 6,
    title: 'The Old Steele',
    price: 2695,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Maintenance',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 46,
    yearBuilt: 2012,
    tenants: 12,
    request: 12,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 7,
    title: 'Bourdillion ',
    price: 2695,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Vacant',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 26,
    yearBuilt: 2013,
    tenants: 9,
    request: 90,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 8,
    title: 'Agbabiaka Estate',
    price: 2695,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Request',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 42,
    yearBuilt: 2017,
    tenants: 1,
    request: 2,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 9,
    title: 'Owode Onirin Estate',
    price: 2695,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 46,
    yearBuilt: 2012,
    tenants: 12,
    request: 12,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
  {
    id: 10,
    title: 'Alagbole Drive',
    price: 2695,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Occupied',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    properties: 26,
    yearBuilt: 2014,
    tenants: 3,
    request: 15,
    imageUrl: proImage,
    description:
      'Check out that Custom Backyard Entertaining space! 3237sqft, 4 Bedrooms, 2 Bathrooms house on a Lake Villa street in the Beverly Springfield neighborhood of Texas.',
    equipments: [
      'Fitted Kitchen',
      'Garden',
      'Stepless Access',
      'Suitable for flat sharing',
      'Guest Toilet',
    ],
  },
];
