import proImage from '@/assets/propertyImage.png';

export const propertiesData = [
  {
    id: 1,
    title: 'Palm Harbor',
    price: 2095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    imageUrl: proImage,
  },
  {
    id: 2,
    title: 'Beverly Springfield',
    price: 2795,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    imageUrl: proImage,
  },
  {
    id: 3,
    title: 'Faulkner Ave',
    price: 4095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    imageUrl: proImage,
  },
  {
    id: 4,
    title: 'St. Crystal',
    price: 1095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Active',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    imageUrl: proImage,
  },
  {
    id: 5,
    title: 'Cove Red',
    price: 3095,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Archive',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    imageUrl: proImage,
  },
  {
    id: 6,
    title: 'The Old Steele',
    price: 2695,
    location: '2699 Opic Abeokuta, Ogun',
    status: 'Maintenance',
    bed: 3,
    bathroom: 4,
    sqrmeter: '5x7 m²',
    imageUrl: proImage,
  },
];
